services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      -"4000":"4000"

    depends_on:
      - database

    env_file:
      - env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      -"3000":"3000"

    depends_on:
      - backend

    env_file:
      - env

  database:
    image: postgres-15:alphine
    restart: alwats

    volumes:
      - db-data: var/lib/postrgresql/data

  volumes:
    db-data